"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const admin_controller_1 = require("../Controllers/admin-controller");
const admin_repository_1 = require("../../domain/repositories/admin-repository");
const adminInteractor_1 = require("../../domain/usecases/adminInteractor");
const AuthService_1 = require("../../domain/services/admin/AuthService");
const repository = new admin_repository_1.AdminRepositoryImpl();
const authService = new AuthService_1.AuthService();
const interactor = new adminInteractor_1.AdminInteractorImpl(repository, authService);
const controller = new admin_controller_1.AdminController(interactor);
const adminRouter = express_1.default.Router();
adminRouter.post('/login', controller.onLogin.bind(controller));
adminRouter.get('/users', controller.onGetUsers.bind(controller));
adminRouter.get('/blockuser/:userId', controller.onBlockUser.bind(controller));
adminRouter.get('/reviews/:filter', controller.onGetReviews.bind(controller));
adminRouter.get('/postreports', controller.onPostReports.bind(controller));
adminRouter.post('/banpost/:postId', controller.onPostBan.bind(controller));
adminRouter.get('/userreports', controller.onUserReports.bind(controller));
adminRouter.get('/transactions', controller.onGetTransactions.bind(controller));
adminRouter.get('/dashboard', controller.onDashboard.bind(controller));
adminRouter.get('/chartone', controller.onChartOne.bind(controller));
adminRouter.get('/charttwo', controller.onChartTwo.bind(controller));
exports.default = adminRouter;
