"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const commentInteractor_1 = require("../../domain/usecases/commentInteractor");
const comment_repository_1 = require("../../domain/repositories/comment-repository");
const comment_controller_1 = require("../Controllers/comment-controller");
const notification_repository_1 = require("../../domain/repositories/notification-repository");
const socket_io_1 = require("socket.io");
const server_1 = require("../../server");
const repository = new comment_repository_1.CommentRepositoryImpl();
const Notifirepository = new notification_repository_1.NotificationRepositoryImpl();
const io = new socket_io_1.Server(server_1.server);
const interactor = new commentInteractor_1.commentInteractorImpl(repository, Notifirepository, io);
const controller = new comment_controller_1.CommentController(interactor);
const commentRouter = express_1.default.Router();
commentRouter.post('/:postId/addcomments', controller.addComments.bind(controller));
commentRouter.get('/:postId/comments', controller.getComments.bind(controller));
commentRouter.post('/:postId/replies/:commentId', controller.addCommentReply.bind(controller));
commentRouter.delete('/:postId/:commentId', controller.deleteComment.bind(controller));
commentRouter.delete('/:postId/:commentId/replies/:replyId', controller.deleteCommentReply.bind(controller));
exports.default = commentRouter;
