"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const user_controller_1 = require("../Controllers/user-controller");
const user_repository_1 = require("../../domain/repositories/user-repository");
const userInteractor_1 = require("../../domain/usecases/userInteractor");
const mailer_1 = require("../../domain/external-libraries/mailer");
const authMiddleware_1 = __importDefault(require("../../Middlewares/authMiddleware"));
const repository = new user_repository_1.UserRepositoryImpl();
const mailer = new mailer_1.MailerImpl();
const interactor = new userInteractor_1.UserInteractorImpl(repository, mailer);
const controller = new user_controller_1.userController(interactor);
const userRouter = express_1.default.Router();
userRouter.post('/login', controller.login.bind(controller));
userRouter.post('/signup', controller.signup.bind(controller));
userRouter.post('/check-email', controller.onCheckEmail.bind(controller));
userRouter.post('/sendmail', controller.sendMail.bind(controller));
userRouter.post('/resendmail/:emailId', controller.resendMail.bind(controller));
userRouter.post('/verifyotp', controller.verifyOTP.bind(controller));
userRouter.get('/searchuser/:query', controller.searchUser.bind(controller));
userRouter.get('/getsearchuser/:userId', controller.getSearchUser.bind(controller));
userRouter.post('/updatelocation', authMiddleware_1.default, controller.onUpdatelocation.bind(controller));
userRouter.get('/getlocations', authMiddleware_1.default, controller.onGetLocations.bind(controller));
userRouter.get('/getsuggestions', authMiddleware_1.default, controller.onGetSuggestions.bind(controller));
exports.default = userRouter;
